import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { classMerge } from "@/lib/utils";
import Header from "@/components/Header";
import HomeIcon from "@/components/homeIcon";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };




export const metadata = {
  // metadataBase: new URL(siteConfig.url),
  title: "Portfolio - Khaled AlKharashy",
  description: "siteConfig.description",
  keywords: "siteConfig.keywords",
  authors: [
    {
      name: "Khaled AlKharashy",
      url: "",
    },
  ],
  creator: "Khaled AlKharashy",
  // themeColor: [
  //   { media: "(prefers-color-scheme: light)", color: "#31456A" },
  //   { media: "(prefers-color-scheme: dark)", color: "#272B30" },
  // ],
  icons: {
    icon: "/k.png",
    // shortcut: "/favicon-16x16.png",
    // apple: "/apple-touch-icon.png",
  },
  // openGraph: {
  //   type: "website",
  //   locale: "en_US",
  //   url: "",
  //   title: "siteConfig.title",
  //   description: "siteConfig.description",
  //   siteName: "siteConfig.name",
  //   images: "/k.png",
  // },
  // twitter: {
  //   card: "summary_large_image",
  //   title: "siteConfig.title",
  //   description: "siteConfig.description",
  //   images: "[siteConfig.ogImage]",
  //   creator: "siteConfig.name",
  // },
  manifest: "/site.webmanifest",
  viewport: "width=device-width, initial-scale=1.0, maximum-scale=1.0",
  alternates: {
    canonical: "/",
  },
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en">
      {/* <GoogleTagManagerHead /> */}

      <body
      // className={classMerge(
      //   // inter.className,
      //   "bg-secondary dark:bg-dark-light",
      // )}
      >
        {/* <div className="bgGridWrapper horizontal"></div>
        <div className="bgGridWrapper vertical"></div> */}
        <main className="lines relative min-h-screen ">
          {/* py-14 px-8 md:py-20 */}
          <div className="line"></div>
          <div className="line"></div>
          <div className="line"></div>

          <link rel="icon" href="/k.png" />

          {/* <Header /> */}
          {children}
          <HomeIcon />
        </main>

        {/* <GoogleTagManagerNoScript /> */}

        <div className="ssr-only">
          {/* {Object.values(siteContent)?.map((content) => content)} */}
        </div>
      </body>
    </html>
  );
}
